### ISSUE TITLE
Implement the QBS files highliting

### ISSUE THREAD

**Issue by denis-shienkov** [denis-shienkov/vscode-qbs#14]

**Comment by rweickelt** [comment]
Using a JSON highlighter for Qbs files should be fine.

**Comment by denis-shienkov** [comment]
I'm thinl, that highlighter engine will produce a syntax errors e.g. for the `import`, `Product {}` and other statements. So, I have planns to use something similar to [QML plugin](https://gitlab.com/vxv/qml).

**Comment by rweickelt** [comment]
So highlighting goes together with linting? Interesting.

**Comment by denis-shienkov** [comment]
Done
