### ISSUE TITLE
No errors when resolving with invalid Qt

### ISSUE THREAD

**Issue by ABBAPOH** [denis-shienkov/vscode-qbs#17]
I installed a new version of Qt and forgot to update qt profile. So, I have a Qt profile which refers to the the non-existing qmake.
When doing project resolve. All I see is 
Resolving project...
Project successfully resolved, elapsed time: 54.70195700228214 msecs.

No errors about that fact that module provider failed to instantiate Qt.

**Comment by rweickelt** [comment]
I see the same. No matter what project I open and what profile is selected, resolving always succeeds.

**Comment by denis-shienkov** [comment]
Guys, I have not ideas why this happens. I do output for all QBS messages into `QBS Output` pane.. Maybe just QBS does not report about the errors in this case.

**Comment by rweickelt** [comment]
@denis-shienkov, the resolve-project command has a reply which contains an error property. https://doc.qt.io/qbs/json-api.html#resolving-a-project conaining [error info](https://doc.qt.io/qbs/json-api.html#errorinfo). Do you look at that?

**Comment by denis-shienkov** [comment]
@rweickelt , yes, of course: https://github.com/denis-shienkov/vscode-qbs/blob/master/src/qbssession.ts#L212

**Comment by rweickelt** [comment]
> The incoming project-resolved response never contains the error field.

That's because [you set errorHandlingMode to "relaxed"](https://github.com/denis-shienkov/vscode-qbs/blob/036ebd0241682cfe8a4daa71c6a2741b8b47c11b/src/qbssessionprotocol.ts#L54)

[The documentation says](https://doc.qt.io/qbs/json-api.html#resolving-a-project):

> The error-handling-mode specifies how Qbs should deal with issues in project files, such as assigning to an unknown property. The possible values are "strict" and "relaxed". In strict mode, Qbs will immediately abort and set the reply's error property accordingly. In relaxed mode, Qbs will continue to resolve the project if possible. A warning message will be emitted for every error that was encountered, and the reply's error property will not be set. The default error handling mode is "strict".

**Comment by denis-shienkov** [comment]
> That's because you set errorHandlingMode to "relaxed"

Maybe. I take it from the QtCreator implementation, there this mode is always `relaxed` (see QtC sources for QBS plugin).

But, the user can cange this mode from the VSCode plugin settings and set to `strict' (by default there is `relaxed`).

**Comment by rweickelt** [comment]
In relaxed mode, Qbs will emit warning messages containing error info objects. They are parsed here: https://github.com/qt-creator/qt-creator/blob/6477a07654bdd498282953d8fc85c2a3e74086af/src/plugins/qbsprojectmanager/qbssession.cpp#L496

**Comment by denis-shienkov** [comment]
Guys, I have missed the handling for the `warning` messages. Now it was fixed, and this messages will be shown on the `QBS Compile` pane.
