### ISSUE TITLE
Hide "Provisioning Profiles" group from tree

### ISSUE THREAD

**Issue by ABBAPOH** [denis-shienkov/vscode-qbs#18]
On macOS, I see an empty "Provisioning Profiles" group in every Product. It comes from xcode.qbs:

    Group {
        name: "Provisioning Profiles"
        prefix: xcode.provisioningProfilesPath + "/"
        files: ["*.mobileprovision", "*.provisionprofile"]
        fileTags: ["xcode.provisioningprofile"]
    }

I don't think we should display it at all.

**Comment by denis-shienkov** [comment]
so, do you suggest to do not display an empty groups (which are does not contains the artifacts)?

**Comment by denis-shienkov** [comment]
Could you please check again?
