### ISSUE TITLE
Implement the project auto-resolving when a qbs/js file changes

### ISSUE THREAD

**Issue by denis-shienkov** [denis-shienkov/vscode-qbs#2]
QBS provides an information about the files, which should be watched for the changes. These files are locates in the `build-system-files` key, and comes from the QBS response.

So, we need to watch the changes for this files and then start the auto resolving.

**Comment by j-ulrich** [comment]
When a source file changes? You mean when a .qbs file changes, right?

**Comment by denis-shienkov** [comment]
Yea, maybe, I don't know yet. ))

**Comment by j-ulrich** [comment]
It shouldn't trigger a resolve when a regular source file changes. Resolving is too expensive in larger projects.
But resolving on .qbs file changes would be reasonable, I guess.
And it should be configurable! So it should be possible to disable the auto-resolving in the extension settings (both on user and on workspace level).

**Comment by denis-shienkov** [comment]
Done.
