### ISSUE TITLE
Wrong order and missing commands in toolbar

### ISSUE THREAD

**Issue by rweickelt** [denis-shienkov/vscode-qbs#20]
The toolbar shows currently _Build_, _Resolve_, and _Collapse All_ in this order.

![image](https://user-images.githubusercontent.com/7616017/97489157-79253080-195f-11eb-9046-0378dc147d91.png)

The _Resolve_ command should come first, then _Build_

The following actions are missing. 

- _Clean_
- _Resolve and Force Probe Execution_

Whether we need explicit _Rebuild_ or not is debatable. No icons are needed for these actions, but a drop-down list like the CMake extension has:
![image](https://user-images.githubusercontent.com/7616017/97490217-d66db180-1960-11eb-896a-9c733646faf9.png)

**Comment by denis-shienkov** [comment]
> Resolve and Force Probe Execution

I'm not sure. Do we need in this? Because currently we did not have this command implemented at all. I meant, we need copy-paste the current 'resolve' command, add there the 'force-probes' entry.. But, what did with other entries, just copy it from the basic 'resolve' command?

**Comment by denis-shienkov** [comment]
Seems done.

**Comment by rweickelt** [comment]
I mean, resolve and force probe execution is a frequent enough use case. Yes it's the basic reolve command copy-pasted + the force probes option.
