### ISSUE TITLE
Integration with "Problems" panel

### ISSUE THREAD

**Issue by j-ulrich** [denis-shienkov/vscode-qbs#26]
When build errors or warnings occur, they should show up in the "Problems" panel:
![image](https://user-images.githubusercontent.com/1260380/98796834-21310400-240c-11eb-8828-09172b0a3dd7.png)

**Comment by j-ulrich** [comment]
Could be that this simply works if the extension sends its output to the "Terminal" instead of the "Output" panel.

Because in the Terminal, there seems to be some functionality to parse compiler error and warning messages already. Because if I run Qbs via a VSCode task, then the errors and warnings show up in the "Problems" panel.

**Comment by j-ulrich** [comment]
> Could be that this simply works if the extension sends its output to the "Terminal" instead of the "Output" panel.

However, could be that this means that the extension must provide the products as Tasks via a TaskProvider: https://code.visualstudio.com/api/references/vscode-api#tasks

Because on [Tasks](https://code.visualstudio.com/api/references/vscode-api#Task), one can set `problemMatchers`.

But I got the feeling that this actually the right approach. Tasks are the VSCode concept that matches Products in Qbs. They can also have a [TaskGroup](https://code.visualstudio.com/api/references/vscode-api#TaskGroup) ("Build", "Clean", "Test").

**Comment by denis-shienkov** [comment]
To be honest, I don't know how this `problems` page does work yet. Need to see the source code for the `cmake` extension. Besides, seems it handles by the `standard` parsers (AFAIK, in `cmake` extension you can choose this parser, as gcc, msvc and so on). But, seems it will not work with a custom compilers (which are non gcc/msvc).

It is an interesting question. 👍
