### ISSUE TITLE
Empty "Select Debugger" list

### ISSUE THREAD

**Issue by j-ulrich** [denis-shienkov/vscode-qbs#27]
To debug a product, one needs to "QBS: Select Debugger" according to [the documentation](https://github.com/denis-shienkov/vscode-qbs/blob/master/docs/how-to.md#debug-a-product). However, this requires that a [Launch configuration](https://code.visualstudio.com/docs/editor/debugging#_launch-configurations) was created before. Else the selection list for the "QBS: Select Debugger" command is empty.

So either the documentation should be fixed and include (a link to) a guide to setup a launch configuration or the extension should automatically create a launch configuration if there is none yet.

Either way, the documentation should mention which parts of the launch configuration are required. Because, for example, the `program` is overridden by the extension but it is not clear what else is needed/overridden.

**Comment by j-ulrich** [comment]
And maybe the wording should be changed from "Select Debugger" to "Select Launch Configuration" or "Select Run Configuration". Because these are the terms used by VSCode.

**Comment by denis-shienkov** [comment]
> So either the documentation should be fixed and include (a link to) a guide to setup a launch configuration
> Either way, the documentation should mention which parts of the launch configuration are required.

Is it not enough: https://github.com/denis-shienkov/vscode-qbs/blob/master/docs/debug-run.md ?

> the extension should automatically create a launch configuration if there is none yet

Not sure about it. You can create a launch configuration manually using the VSCode gui.

**Comment by j-ulrich** [comment]
> Is it not enough: https://github.com/denis-shienkov/vscode-qbs/blob/master/docs/debug-run.md ?

Ah! I didn't see that! 😃 
Yes that's enough. So I guess we just need to link there from https://github.com/denis-shienkov/vscode-qbs/blob/master/docs/how-to.md#debug-a-product

> Not sure about it. You can create a launch configuration manually using the VSCode gui.

Sure. The auto-creation would just be a convenience for the unexperienced user. But it's not important of course.

**Comment by denis-shienkov** [comment]
> The auto-creation would just be a convenience for the unexperienced user. 

Maybe we can replace `No debugger` with something like `Use automatically`.. And then if this `Use automatically` is set, then we will try to create the debugger config from the compiler name (as currently does in the cmake extension).

**Comment by denis-shienkov** [comment]
The auto creation task here #30

**Comment by denis-shienkov** [comment]
Done, replaced with `Select Launch Configuration`
