### ISSUE TITLE
Use defaultBuildDirectory or make it configurable

### ISSUE THREAD

**Issue by j-ulrich** [denis-shienkov/vscode-qbs#28]
The extension seems to add an additional directory layer on top of the `defaultBuildDirectory`. The additional directory has a name following the pattern `<profile name>_<configuration name>`. 

So the effective build directory is therefore:
```
<path to project>/<defaultBuildDirectory>/<profile_name>_<configuration name>/<configuration name>
```
As one can see, the `<configuration name>` is redundant.

And the question is why the extension differs from Qbs' default behavior which would be a build directory at
```
<path to project>/<defaultBuildDirectory>/<configuration name>
```

**Comment by denis-shienkov** [comment]
> As one can see, the <configuration name> is redundant.

No, the last `<configuration name>` creates automatically at building. This behavior same as in QtCreator.

**Comment by j-ulrich** [comment]
Ah! Okay. I didn't see the extension settings at all! I needed to restart VSCode for the extension settings to show up! That's why I thought the extension does not have any settings yet.
That's weird. Normally the extension settings show up immediately after installing the extension nowadays. 🤔 

But then this issue already works as expected.
