### ISSUE TITLE
Changes to launch configuration are not picked up

### ISSUE THREAD

**Issue by j-ulrich** [denis-shienkov/vscode-qbs#29]
I have one launch configuration and I started debugging with it. However, I forgot to set a `sourceFileMap` in the configuration. So I stopped debugging, added the `sourceFileMap` in the launch configuration and then started debugging of the product again. But the change in the launch configuration was not respected. So the debugger was still not able to find the source file.

When starting the launch configuration directly, the `sourceFileMap` was used as expected.

After restarting VSCode, the change of the launch configuration was respected also when debugging via the Qbs extension.
So it seems that the Qbs extension caches the launch configuration and I guess it shouldn't.

**Comment by denis-shienkov** [comment]
> So it seems that the Qbs extension caches the launch configuration and I guess it shouldn't.

Yes, it is. When you choose the `debugger` name, its configuration sets to the extension. The extension do not re-parses the `launch.json` file until you do not select other `debugger`. 

I'll try to fix it.

**Comment by j-ulrich** [comment]
> re-parse the configuration each time before debugging

I guess that's enough and also what I would expect what is happening.

**Comment by denis-shienkov** [comment]
Done
