### ISSUE TITLE
QBS Compile Output is stealing focus

### ISSUE THREAD

**Issue by j-ulrich** [denis-shienkov/vscode-qbs#37]
While building, the "QBS Compile Output" panel is stealing the focus from the editor whenever a new line of output appears.
This makes it impossible to work while building.

A quick search suggests that the extension should set `preserveFocus` to `true` when calling `show()` to show the panel. See https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L5346

**Comment by denis-shienkov** [comment]
Thanks, done.
