### ISSUE TITLE
"QBS executable not found" on MacOS

### ISSUE THREAD

**Issue by sergey-uvarov** [denis-shienkov/vscode-qbs#42]
The path provided in Qbs path field is valid. I build the same project with this executable using Qt Creator and everything works fine. However I keep getting an error when trying to run any command in Command Palette. And the session can't start.
<img width="565" alt="Screenshot 2021-06-13 at 20 07 36" src="https://user-images.githubusercontent.com/85841795/121816341-b4246c00-cc83-11eb-9c51-1df1560cc361.png">
<img width="398" alt="Screenshot 2021-06-13 at 20 09 04" src="https://user-images.githubusercontent.com/85841795/121816342-b4bd0280-cc83-11eb-9fa8-f22a6c559b65.png">
<img width="557" alt="Screenshot 2021-06-13 at 20 07 14" src="https://user-images.githubusercontent.com/85841795/121816344-b5559900-cc83-11eb-998f-b47d807623d4.png">

**Comment by denis-shienkov** [comment]
OSX does not support an executable files with `exe` extension (because it is used only in Windows). 
Seens, you need to download the QBS package for OSX if you want to work with QBS on OSX.

**Comment by ABBAPOH** [comment]
Indeed, the .exe extension looks very strange.
You can either use the qbs binaries shipped with QtCreator (e.g. "/Applications/Qt/Qt Creator.app/Contents/MacOS/qbs")
or install it via Brew:
$ brew install qbs
$ /usr/local/bin/qbs --version

**Comment by sergey-uvarov** [comment]
Well, yes, I know that .exe files are not supported by macOS 
But we use this executable to build projects on Windows, MacOS and Ubuntu 
Everything works well with QtCreator, but using your extension I can’t use this executable. I can use qbs package for Mac, but I wonder why it is working in one way, but doesn’t work in another

**Comment by sergey-uvarov** [comment]
I tried qbs package for Mac from qt site. It doesn't work either.
<img width="261" alt="Screenshot 2021-06-14 at 17 56 37" src="https://user-images.githubusercontent.com/85841795/121913380-06c05f80-cd3a-11eb-9ad8-76f7ed06d047.png">
<img width="513" alt="Screenshot 2021-06-14 at 17 55 53" src="https://user-images.githubusercontent.com/85841795/121913394-09bb5000-cd3a-11eb-8ffb-550dbb68bf9d.png">
<img width="513" alt="Screenshot 2021-06-14 at 17 55 30" src="https://user-images.githubusercontent.com/85841795/121913402-0a53e680-cd3a-11eb-8e70-a90a1667aff7.png">

**Comment by ABBAPOH** [comment]
No, the one that can be downloaded from the website https://download.qt.io/official_releases/qbs/1.19.0/ doesn't work (unless you disable codesign check - we do not have unfortunately, we do not have certificate we can use to sign it).
Can you try the one that is shipped with Qt Creator (as it is working for you?)
Do you get any errors in vscode?

**Comment by sergey-uvarov** [comment]
It worked, thank you!
