### ISSUE TITLE
Use Run target as Build one

### ISSUE THREAD

**Issue by sevoster** [denis-shienkov/vscode-qbs#64]
Hi,

Currently there are two separate targets for Build and Run and it's not very comfortable to sync them manually.
It would be nice to have some option to use one target product for both building and running.

Also an option to always build target before running would be great.

**Comment by denis-shienkov** [comment]
> Currently there are two separate targets

That's done by analogy with the `cmake-tools` extension.

**Comment by denis-shienkov** [comment]
I think, that `qbs.buildBeforeRun` will be enouth, thanks, done.
