### ISSUE TITLE
QBS fails to detect profiles on MacOS

### ISSUE THREAD

**Issue by panbolo** [denis-shienkov/vscode-qbs#70]
Hello, I just found an issue with using latest extension version on my mac (2.0.1) with qbs 1.24.0.

While running from terminal: qbs build profile:clang I am building fine. But with VS Code extension when I choose option to scan for build profiles in the terminal I get CLANG and LLVM-GCC detected, but in selection drop-down I only see Default, that points to nothing.

**Comment by panbolo** [comment]
Just tested the older version 1.0.7 and this one does not suffer form the same problem.

**Comment by denis-shienkov** [comment]
Could you please provide:

* a full resulting output for the *scan build profiles* command from the *VSCode output pane*
* a full resulting output for the `qbs-config --list` command, running from the separate terminal (or from the VSCode terminal)

**Comment by panbolo** [comment]
Output from scan build profiles:
`Starting build profiles scanning...
	Trying to detect gcc...
	Profile 'llvm-gcc' created for '/usr/bin/llvm-gcc'.
	Trying to detect clang...
	Profile 'clang' created for '/usr/bin/clang'.
	Trying to detect IAR toolchains...
	No IAR toolchains found.
	Trying to detect KEIL toolchains...
	No KEIL toolchains found.
	Trying to detect SDCC toolchains...
	No SDCC toolchains found.
	Trying to detect COSMIC toolchains...
	No COSMIC toolchains found.
	Trying to detect DMC toolchains...
	Trying to detect WATCOM toolchains...
	No WATCOM toolchains found.
Build profiles scanning finished.`

**Comment by panbolo** [comment]
Output from qbs-config --list:

>profiles.clang.cpp.toolchainInstallPath: "/usr/bin"
profiles.clang.qbs.toolchainType: "clang"
profiles.llvm-gcc.cpp.archiverPath: "/usr/bin/ar"
profiles.llvm-gcc.cpp.assemblerPath: "/usr/bin/as"
profiles.llvm-gcc.cpp.dsymutilPath: "/usr/bin/dsymutil"
profiles.llvm-gcc.cpp.nmPath: "/usr/bin/nm"
profiles.llvm-gcc.cpp.stripPath: "/usr/bin/strip"
profiles.llvm-gcc.cpp.toolchainInstallPath: "/usr/bin"
profiles.llvm-gcc.cpp.toolchainPrefix: "llvm-"
profiles.llvm-gcc.qbs.toolchainType: "llvm"
profiles.qt-0-0-0.baseProfile: "clang"
profiles.qt-0-0-0.moduleProviders.Qt.qmakeFilePaths: ["/opt/homebrew/bin/qmake"]

**Comment by panbolo** [comment]
Also if that helps, I very similar output on my Linux workstation and it works like a charm.

**Comment by denis-shienkov** [comment]
Thanks, fixed in next v2.0.2 (you can install it manually from the release tags in github, or wait until the extension be updated in VS marketplace)
