### ISSUE TITLE
Empty profiles are not recognized

### ISSUE THREAD

**Issue by Psy-Kai** [denis-shienkov/vscode-qbs#71]
Since version 2.0.0 it is not possible to select a empty profile. Declaring empty profiles is my current work-around for using profiles declared in the project via https://qbs.io/docs/qml-qbslanguageitems-profile/.

To declare an empty profile just use `qbs-config profiles.myProfile undefined`.

PS: I dont know if it is possible to query all profiles declared in the project files and provide them via the profile selector. This would even be a much better solution.

**Comment by Psy-Kai** [comment]
This snapshot fixes it, thanks for the fast fix 😃

**Comment by denis-shienkov** [comment]
Very good ))
