### ISSUE TITLE
Run and Debug failes with "error while loading shared libraries:"

### ISSUE THREAD

**Issue by Psy-Kai** [denis-shienkov/vscode-qbs#72]
Running an application which uses shared libraries does not work anymore (I think since version 2 of the extension). Version `1.0.7` works flawless.
On Linux the application starts but immediately crashes with an "error while loading shared libraries:" warning.

This bug occurs on Linux and Windows.

**Comment by denis-shienkov** [comment]
1. Do you meant when `Run` or `Debug` target, or both?
2. Do you use any `env` variables in the `launch.json` file?

**Comment by Psy-Kai** [comment]
I mean both and I don't have any value in the `env` array.  
With version `1.0.7` the following `launch.json` works just fine:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${command:qbs.getProductExecutablePath}",
            "args": [
                "--plugins-searchpaths",
                "${command:qbs.getBuildDirectory}/install-root/usr/local/lib/<rest-of-path-masked-out-here>",
            ],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                },
                {
                    "description": "Set Disassembly Flavor to Intel",
                    "text": "-gdb-set disassembly-flavor intel",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}
```

PS: I know that the `${command:qbs.getBuildDirectory}` does not work with version `2.x.y` but even with `${command:qbs.getProductBuildDirectory}` it does not start.

**Comment by denis-shienkov** [comment]
Hmm, but to launch the application with the shared libraries, you need:
* on Linux : or `RPATH`, or use `LD_LIBRARY_PATH` env
* on Windows : or library in same directory as executable, or use `PATH` env

What's structure of your compiled application?

**Comment by Psy-Kai** [comment]
My experience is that this is all handled automatically (e.g. in QtC). And version `1.` of the extension handled this somehow too. Does `qbs run` automatically set `PATH`?

**Comment by denis-shienkov** [comment]
Do you use the Qt application 2with the plugins? Or just a shared libraries?

> Just using the Qt framework (with all its dynamic libs) will not run.

Ahh, can I reproduce it with a just simple Qt console-application?

**Comment by Psy-Kai** [comment]
Should be reproducible whit that. I will try too.

**Comment by Psy-Kai** [comment]
I have uploaded a minimal example project: https://github.com/Psy-Kai/vscode-qbs_issue-72

**Comment by denis-shienkov** [comment]
Your example is not compiled for me. So, can you please test this issue with the `app-and-lib` example from the Qbs sources?

**Comment by denis-shienkov** [comment]
Thanks. Could you please install the attached `qbs-tools-2.1.3.vsix` package and check now?
[qbs-tools-2.1.3.zip](https://github.com/denis-shienkov/vscode-qbs/files/11505208/qbs-tools-2.1.3.zip

PS: Just unpack from the ZIP to VSIX before.
