### ISSUE TITLE
Cannot run/debug product with arguments from launch.json

### ISSUE THREAD

**Issue by Psy-Kai** [denis-shienkov/vscode-qbs#73]
The [arguments](https://code.visualstudio.com/docs/cpp/launch-json-reference#_args) set in `launch.json` are not used when running ~~/debugging~~ the application via the Qbs-extension.

Edit: How to run (not debug) the application using a launch configuration? With `QBS Debug` it uses `args` from `launch.json`. With `QBS Run` it does not use `args`.

**Comment by denis-shienkov** [comment]
AFAIK, the VSCode does not support the arguments to  Run the application. This even does not implemented and in the CMake extension: https://github.com/microsoft/vscode-cmake-tools/blob/main/src/cmakeProject.ts#L2325
