### ISSUE TITLE
error processing launch options at field value

### ISSUE THREAD

**Issue by q517470045** [denis-shienkov/vscode-qbs#74]
When I click the debug button, the error appears as above, it seems to be a problem in the launch file, but there is no` value `parameter in my **`launch.json`** file, I can't locate where the problem is, please help me thanks!

**Comment by q517470045** [comment]
![image](https://user-images.githubusercontent.com/56730549/236364261-5384422b-f656-43e5-a631-e0e63bb670d0.png)

**Comment by denis-shienkov** [comment]
Please provide your `launch.json` file

**Comment by q517470045** [comment]
> Please provide your `launch.json` file

"version": "0.2.0",
    "configurations": [
        {
            "name": "vis",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${workspaceFolder}/build/MSVC2019-x86_x64_debug/debug/install-root/mmind_viz_debug.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            "environment": [],
            "console": "internalConsole",
            "visualizerFile": "${workspaceRoot}/.vscode/qt5.natvis",
        },
        {
            "name": "planning_test",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${workspaceFolder}/build/MSVC2019-x86_x64_debug/debug/install-root/mmind_planner_test_debug.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            "environment": [],
            "console": "internalConsole",
            "visualizerFile": "${workspaceRoot}/.vscode/qt5.natvis"
        }
    ]
**Sorry for my negligence**

**Comment by q517470045** [comment]
> 

I have solved this error, thanks!

**Comment by denis-shienkov** [comment]
Ok, then I close this task.
